[PHONE-SS-CPU0]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu0
polling		500
trig		  33000   47000
clr		    32000   46000
target		1190400 691200

[PHONE-SS-CPU4]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu4
polling		500
trig		  34000   47000
clr		    31000   46000
target		1056000 806400

[PHONE-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		1000
trig		  25000	45000
clr		    24000	43000
target		1616	1717


[PHONE-MONITOR-LCD]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		backlight
polling		1000
trig	    41000	43000	46000
clr	      40000	42000	45000
target	  12	100  155


[PHONE-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		1000
trig	    45000	    51000
clr	      44000	    49000
target	  10100000	12500001

[PHONE-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		boost_limit
polling		1000
trig		  25000
clr		    24000
target		1

[PHONE-MONITOR-BCL]
algo_type	monitor
sensor		BAT_SOC
device		hotplug_cpu2+hotplug_cpu3
polling		1000
trig		  5
clr		    6
target		1+1
reverse		1
