# ====================================================================
# MODIFIED THERMAL CONFIG - GAME TURBO (tgame)
# Device: Redmi Note 12 4G (topaz / tapas) - Snapdragon 685 (SM6225)
# Preset: Gaming / High Performance
# ====================================================================

[TGAME-SS-CPU0]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu0
polling	  1000
trig	    48000	  50000	  52000  	54000	  56000
clr	      46000	  48000	  50000	  52000	  54000
target	  1900800	1804800	1516800	1190400	940800

[TGAME-SS-CPU4]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu4
polling		1000
trig	    46000	  49000	  52000	  54000	  56000
clr	      44000	  47000	  50000	  52000	  54000
target	  2592000	2208000	1766400	1536000	1344000

[TGAME-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling	  1000
trig	    42000	43000	44000	45000	46000	47000	48000	49000	50000	51000
clr     	41000	42000	43000	44000	45000	46000	47000	48000	49000	50000
target	  301	  402	  607  	712	  912		1013	1113	1214	1414	1515

[TGAME-MONITOR-LCD]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		backlight
polling	  1000
trig	    60000	63000	65000
clr	      58000	61000	63000
target	  12	  70   130

[TGAME-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device	  temp_state
polling	  1000
trig	    50000	    52000			56000
clr	      48000	    50000			54000
target	  10100000	10100004	12500001

[TGAME-MONITOR-BCL]
algo_type	monitor
sensor		BAT_SOC
device		hotplug_cpu2+hotplug_cpu3
polling		1000
trig		  3
clr			  4
target		1+1
reverse		1

# Disabled core hotplugging
[TGAME-MONITOR-CCC_CTRL]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu2+hotplug_cpu3
polling		1000
trig		  65000
clr			  62000
target		1+1

[TGAME-MONITOR-CCC_CTRL-1]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu6+hotplug_cpu7
polling		1000
trig		  65000
clr			  62000
target		1+1

[TGAME-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor	  VIRTUAL-SENSOR
device	  boost_limit
polling	  2000
trig	    54000
clr	      52000
target	  1
